name: CI

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: install
        run: yarn install

      - name: test
        run: yarn lint

      - name: build
        run: yarn build

      # used in many webcomps
      # - name: REUSE Compliance Check
      #   uses: fsfe/reuse-action@v1
